version: 0.2
phases:
  build:
    commands:
      - chmod +x script.sh
      - ./script.sh $SOURCE_IMAGE_FILE $AWS_REGION $ACCOUNT_ID
  post_build:
    commands:
      - cat Output
      - aws s3 cp Output s3://$OUTPUT_S3_BUCKET/
